version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data_checker_app
    ports:
      - "5000:5000"
#    volumes:
#      - .:/app
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:5000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    
